# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jailbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateField(null=True)),
                ('book_time', models.TextField(null=True)),
                ('birth_date', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.TextField(null=True)),
                ('race', models.TextField(null=True)),
                ('number', models.TextField(null=True)),
                ('direction', models.CharField(max_length=30, null=True)),
                ('street', models.TextField(null=True)),
                ('suffix', models.CharField(max_length=30, null=True)),
                ('city', models.TextField(null=True)),
                ('state', models.TextField(null=True)),
                ('zipcode', models.TextField(null=True)),
                ('statute', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('court_date', models.DateField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('bond', models.FloatField(null=True)),
            ],
        ),
    ]
