# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
'''
    operations = [
        migrations.CreateModel(
            name='Arrest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrestee_id', models.IntegerField()),
                ('arrest_date', models.DateField()),
                ('arrest_time', models.TimeField()),
                ('arrest_code', models.TextField()),
                ('arrest_location', models.TextField()),
                ('crime_code', models.TextField()),
                ('crime_code_description', models.TextField()),
                ('crime_code_category', models.TextField()),
                ('crime_code_category_description', models.TextField()),
                ('weapon_code_1', models.CharField(max_length=30)),
                ('weapon_code_2', models.CharField(max_length=30)),
                ('weapon_code_3', models.CharField(max_length=30)),
                ('race', models.TextField()),
                ('sex', models.TextField()),
                ('age', models.IntegerField()),
                ('employment_code', models.CharField(max_length=30)),
                ('arrest_officer_code', models.IntegerField()),
                ('result', models.TextField()),
                ('jurisdiction', models.TextField()),
                ('more_than_one_charge', models.IntegerField()),
                ('mvo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
            ],
        ),
    ]
'''